#!/usr/bin/env ruby
require "rubygems"
require "bundler/setup"
require "mailman"

#Mailman.config.logger = Logger.new("log/mailman.log")

Mailman.config.imap = {
  server: 'imap.qhoekman.nl', port: 143,
  username: "tedx@qhoekman.nl",
  password: "dmec2012"
}

Mailman::Application.run do
  default do
    begin
      Hookup.receive_mail(message)
    rescue Exception => e
      Mailman.logger.error "Exception occurred while receiving message:\n#{message}"
      Mailman.logger.error [e, *e.backtrace].join("\n")
    end
  end
end
